actions:
  1:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-notification-3.0-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-notification
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-notification-3.0-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-notification-3.0
  2:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-product-type-1.0-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-product-type
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-product-type-1.0-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-type-1.0
  3:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-supplier-1.0-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-supplier
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-supplier-1.0-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-supplier-1.0
  4:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-brand-1.0-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-brand
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-brand-1.0-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-brand-1.0
  5:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-retailer-3.1-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-retailer
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-retailer-3.1-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-retailer-3.1
  6:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-tag-1.0-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-tag
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-tag-1.0-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-tag-1.0
  7:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-customer-1.4-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-customer
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-customer-1.4-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-customer-1.4
  8:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-product-1.7-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-product
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-product-1.7-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-1.7
  9:
    action: snapshot
    description: >-
      Snapshot company-* prefixed indices with the default snapshot name pattern of
      'company-register_sale-3.1-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: kereru-snapshot-s3-register_sale
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-register_sale-3.1-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-register_sale-3.1
  10:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-notification-3.0-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-notification
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-notification-3.0
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  11:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-product-type-1.0-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-product-type
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-type-1.0
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  12:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-supplier-1.0-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-supplier
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-supplier-1.0
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  13:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-brand-1.0-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-brand
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-brand-1.0
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  14:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-retailer-3.1-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-retailer
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-retailer-3.1
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  15:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-tag-1.0-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-tag
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-tag-1.0
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  16:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-customer-1.4-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-customer
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-customer-1.4
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  17:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-product-1.7-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-product
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-1.7
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
  18:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-register_sale-3.1-*' prefixed snapshots.
    options:
      repository: kereru-snapshot-s3-register_sale
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-register_sale-3.1
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 14
