actions:
  1:
    action: close
    description: "Close selected indices company-notification-3.0 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-notification-3.0
  2:
    action: restore
    description: >-
      Restore all indices in the most recent company-notification-3.0-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-notification
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-notification-3.0
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  3:
    action: close
    description: "Close selected indices company-product-type-1.0 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-type-1.0
  4:
    action: restore
    description: >-
      Restore all indices in the most recent company-product-type-1.0-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-product-type
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-type-1.0
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  5:
    action: close
    description: "Close selected indices company-supplier-1.0 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-supplier-1.0
  6:
    action: restore
    description: >-
      Restore all indices in the most recent company-supplier-1.0-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-supplier
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-supplier-1.0
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  7:
    action: close
    description: "Close selected indices company-brand-1.0 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-brand-1.0
  8:
    action: restore
    description: >-
      Restore all indices in the most recent company-brand-1.0-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-brand
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-brand-1.0
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  9:
    action: close
    description: "Close selected indices company-retailer-3.1 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-retailer-3.1
  10:
    action: restore
    description: >-
      Restore all indices in the most recent company-retailer-3.1-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-retailer
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-retailer-3.1
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  11:
    action: close
    description: "Close selected indices company-tag-1.0 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-tag-1.0
  12:
    action: restore
    description: >-
      Restore all indices in the most recent company-tag-1.0-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-tag
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-tag-1.0
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  13:
    action: close
    description: "Close selected indices company-customer-1.4 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-customer-1.4
  14:
    action: restore
    description: >-
      Restore all indices in the most recent company-customer-1.4-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-customer
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-customer-1.4
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  15:
    action: close
    description: "Close selected indices company-product-1.7 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-1.7
  16:
    action: restore
    description: >-
      Restore all indices in the most recent company-product-1.7-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-product
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-product-1.7
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
  17:
    action: close
    description: "Close selected indices company-register_sale-3.1 before restoring snapshot"
    options:
      continue_if_exception: True
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-register_sale-3.1
  18:
    action: restore
    description: >-
      Restore all indices in the most recent company-register_sale-3.1-* snapshot with state
      SUCCESS.  Wait for the restore to complete before continuing.  Skip
      the repository filesystem access check.  Use the other options to define
      the index/shard settings for the restore.
    options:
      repository: kereru-snapshot-s3-register_sale
      # Leaving name blank will result in restoring the most recent snapshot by age
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      include_aliases: False
      ignore_unavailable: False
      include_global_state: False
      partial: False
      extra_settings:
        index_settings:
          number_of_replicas: 2
      wait_for_completion: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-register_sale-3.1
        exclude:
      - filtertype: state
        state: SUCCESS
        exclude:
