actions:
  1:
    action: snapshot
    description: >-
      Snapshot company-index-A-* prefixed indices with the default snapshot name pattern of
      'company-index-A-%Y%m%d%H%M'.  Wait for the snapshot to complete.  Skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: snapshot-s3-index-A
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      name: company-index-A-%Y%m%d%H%M
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: ${WAIT:False}
      continue_if_exception: True
      skip_repo_fs_check: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-index-A
  2:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 14 days
      (based on creation_date), for 'company-index-A-*' prefixed snapshots.
    options:
      repository: snapshot-s3-index-A
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M'
      disable_action: False
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: company-index-A
      - filtertype: age
        source: creation_date
        direction: older
        unit: ${UNIT:days}
        unit_count: ${UNIT_COUNT:14}
