client:
  hosts:
    - ${ELASTICSEARCH_HOST:127.0.0.1}
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  username:
  password:
  timeout: ${CLIENT_TIMEOUT:30}
  master_only: False

logging:
  loglevel: ${LOGLEVEL:INFO}
  logfile:
  logformat: default
  blacklist: ["elasticsearch", "urllib3"]
